### ISSUE TITLE
Update Semantic UI version

### ISSUE THREAD

**Issue by maxmcc** [hack4impact/flask-base#1]
- Update SemUI version to track post 2.0.0 bugfixes
- Include separate SCSS files (perhaps from port at https://github.com/doabit/semantic-ui-sass) so that the whole framework doesn't have to be included, just the modules that are being used.

**Comment by abhisuri97** [comment]
Is anyone interested in taking this on?

**Comment by Hiyorimi** [comment]
@abhisuri97 @sandlerben Can you take a look at #174 and also close this one please?

**Comment by abhisuri97** [comment]
resolved.
