### ISSUE TITLE
Bad solution for secrets keys

### ISSUE THREAD

**Issue by soshnikov** [hack4impact/flask-base#101]
Sorry for my bad english, but I hope you understand my Python.
You have big security problem with `SECRET_KEY` in config. Most of your users will not change secrets.
Every copy of application must have own secret ceys generated automatically.

````python
def generate_secret(key_len=128):
    """
    Generate secret key
    :param key_len: length of the key
    :return:
    """
    dictionary = string.ascii_letters + string.digits + string.punctuation
    return ''.join((choice(dictionary) for _ in range(key_len)))


def get_secret(secret_file, key_len=128):
    """
    Get saved secret from file or generate new and save it
    :param secret_file: filename for store secret key
    :param key_len: how long key generate?
    :return:
    """
    if os.path.isfile(secret_file):
        fd = open(secret_file, 'r')
        secret = fd.read()
    else:
        secret = generate_secret(key_len)
        fd = open(secret_file, 'w')
        fd.write(secret)
    fd.close()
    return secret
````
And...

````python
    APP_ROOT = os.path.dirname(__file__)
    secrets_folder = os.path.join(APP_ROOT, '..', '.secrets')
    SECRET_KEY = get_secret(os.path.join(secrets_folder, '.secrets'))
````

This case save secret keys for every installation in special folder. This folder we can add as volume in Docker.

For testing & development we need generate data for our local installation. It's not 	
comfortably, but it's most secure.

**Comment by abhisuri97** [comment]
Note that when flask-base is launched in the production configuration (i.e. `FLASK_CONFIG=production`) we assert that the SECRET_KEY environment variable must be set (https://github.com/hack4impact/flask-base/blob/master/config.py#L72). The application will not run in the setting if the SECRET_KEY is not set. Does this address your concerns?

**Comment by abhisuri97** [comment]
However, I would be willing to consider adding the `generate_secret` method as a `manage.py` command if it sets the environment variables itself.

**Comment by soshnikov** [comment]
I don't understand how we can use `manage.py` command for maintance docker container.
Dockerfile is ouside of docker environment.
Well, we can use this command for manually generate secrets. But main idea is generate secrets automatically for every installation of application.
I'm shure, it's needed to keep away user or admin from this moment. Remove _human factor_ as far as possible.

Thank you for answers. I'm shure, you choose best way for your awesome project.

**Comment by abhisuri97** [comment]
So, I am against writing it to a file just because it is an anti pattern for heroku launches. But one potential solution I can get running is just to generate a SECRET_KEY on each app run and not have it pull from any configs etc. Would that serve your needs? (and I feel it would just lighten the configuration needed to be done by the user)

**Comment by sandlerben** [comment]
Abhi I believe that will break cookies (e.g user sessions)

**Comment by soshnikov** [comment]
heroku... 
Don't know. Think docker more modern & necessary.
may be I understend U wrong, but we can't change secret key - passwords and other things which use secket keys will be broken.
Secrets must be generated once only for the installation. And I don't see another way to keep this against files. Files is for keep data, During applicarion run we create a lot of files, It's OK, We need save our data. Secrets is the same data.

**Comment by abhisuri97** [comment]
Okay, so I took a look at setting up flask-base on docker and our current solution works fine
I will just outline it for future reference:
- create a `config.env` file
- make sure it contains the following environment variable `FLASK_CONFIG=production`
- make sure it contains a `SECRET_KEY`. *If it does not contain a secret key, the application will trip the assert check for a secret key in the environment.

Flask-base will read from this `config.env` file and load the variables in that file as environment variables.

you can check out some more details about how to launch in our [documentation](https://hack4impact.github.io/flask-base/deploy/) (the instructions are for heroku, but are somewhat applicable to Docker). 

However, I would like to see a `generate_secret_key` command in our `manage.py` file. I.e. the user can call `python manage.py generate_secret_key` and a sufficiently random secret key should be appended into the `config.env` file (and throw an error if one already exists in the file). Feel free to make a PR for this

If you have any further concerns, feel free to reopen the PR.

**Comment by soshnikov** [comment]
No, i think your decision is good.
Tank you.
