### ISSUE TITLE
Using flask-base as a base for a new project?

### ISSUE THREAD

**Issue by npezolano** [hack4impact/flask-base#102]
What's the recommended way to use flask-base as the base for a new project? It seems if you use `git clone` then copy paste the files into your new project, you will lose track of updates and fixes.

Would `git submodule add -b master https://github.com/hack4impact/flask-base` be the preferred method?

**Comment by sandlerben** [comment]
Great question. What I have done, which may not be the best approach, is set two remotes in the downstream project named `origin` and `flask-base`. `origin` points to your project's repository and `flask-base` points to this repository. This way, you can cherry-pick any flask-base commits you want (just `git fetch` first).

**Comment by sandlerben** [comment]
Oh, and I don't think submodules is the right solution to the problem. From what I understand, they require that the submodule be kept in a subdirectory. Plus, once you fork off of flask-base, you may make changes which conflict with flask-base changes, or you may not want to include all upstream changes.

**Comment by npezolano** [comment]
True, Ideally you want to be able to pull updates from flask-base and not commit to it. Commits for fixes could be sent separately.

**Comment by sandlerben** [comment]
Right. So the workflow could be something like this.

1. Do work normally using feature branches, pull requests, etc.
2. Occasionally make a feature branch where you can cherry-pick specific flask-base changes.
3. Make a pull request for those changes like you normally would.

**Comment by abhisuri97** [comment]
Closing issue. Feel free to reopen/create a new issue if you have further questions.
