### ISSUE TITLE
Add Flask-Base to Awesomo list.

### ISSUE THREAD

**Issue by lk-geimfari** [hack4impact/flask-base#104]
How about add it to list?

`awesomo` [here](https://github.com/lk-geimfari/awesomo)

If you add it to list, you can find more contributors for your project.

**Comment by abhisuri97** [comment]
Yeah, that'd be great 👍. I noticed that you typically do the commits on the python.md file. Would you mind adding ours? if not, we can make a PR.

**Comment by lk-geimfari** [comment]
@abhisuri97 It's done!
