### ISSUE TITLE
switch to honcho instead of foreman

### ISSUE THREAD

**Issue by sobolevn** [hack4impact/flask-base#105]
I really like this setup! But not the `gem` part. 
`foreman` provides [alternatives for different languages](https://github.com/ddollar/foreman#ports).

It suggests using [`honcho`](https://github.com/nickstenning/honcho) as a replacement for `python`.
Are there any drawbacks? Thanks!

**Comment by abhisuri97** [comment]
Thanks for suggesting honcho, it looks like a great tool. But right now our needs are served well by foreman. If you feel that there is some specific disadvantage to foreman or some specific advantage to honcho, please reopen the Issue or feel free to make a Pull Request.

**Comment by sandlerben** [comment]
@abhisuri97 `honcho` implements the foreman API. The only practical difference of changing the README to mention `honcho` is that one could run the project without a ruby dependency (and with a pure python tool). I personally use `forego`, another drop-in replacement for foreman written in Go.

**Comment by sandlerben** [comment]
Thanks for mentioning this @sobolevn.

**Comment by abhisuri97** [comment]
done. thanks for the suggestion 👍
