### ISSUE TITLE
jquery not defined

### ISSUE THREAD

**Issue by Mattpwinchester** [hack4impact/flask-base#109]
Hi everyone,

I haven't done Flask web deployments before and I started using this code base with limited Flask knowledge. After working with the code base to get it to the point where I want to deploy it on for cloud testing, I found that the javascript functions were not working for the about page and the top right slider for the mobile view:

![console_error](https://cloud.githubusercontent.com/assets/20302042/22806836/5ff45c3c-eefa-11e6-9a04-2ac187909114.jpg)

The only changes/differences between my local copy and the online deployment are that the online deployment has a different port number and is connected via upstream from a nginx web server. I enabled gzip javascript for nginx with these lines:

http {
...

        gzip on;
        gzip_disable "msie6";
        gzip_types application/x-javascript;

...
}

If you need any additional information feel free to email me.

**Comment by abhisuri97** [comment]
Can you try checking out #110 and see if that fixes your problem? I have not been able to reproduce it on my machine, but it is most likely due to the fact that we don't put an explicit order to how scripts are bundled in `app/assets.py`.

**Comment by abhisuri97** [comment]
Resolved ref #110
