### ISSUE TITLE
Semantic-ui width always fits width of screen

### ISSUE THREAD

**Issue by Mattpwinchester** [hack4impact/flask-base#113]
I'm new to semantic-ui and when I try to build a table of information from the database it works but the width of the table is always the width of the browser. I tried various settings such as setting the 'width' variable or setting class as "ui celled striped table ten wide". Even placing it in a container and doing the same had no effect. What can I do to customize the width of a table/container in a view?

**Comment by abhisuri97** [comment]
Hmm. I can't speak to the specifics of this, but you can look at https://github.com/hack4impact/flask-base/blob/master/app/templates/admin/registered_users.html for an example of a table we use to display all users on the admin side.

**Comment by Mattpwinchester** [comment]
Fixed by wrapping my code in 
        

```
<div class="ui stackable grid container">
                <div class="sixteen wide tablet ten wide computer centered column">
</div>
</div>
```

Not sure why I have to wrap the table in this though. On the semantic-ui website documentation it states that I can control the table width using the "width" element or stating the column size in the div class of the table.
