### ISSUE TITLE
"GET /static/webassets-external/zxcvbn.js.map HTTP/1.0" 404

### ISSUE THREAD

**Issue by Mattpwinchester** [hack4impact/flask-base#118]
The server is running fine from what I can see. However, there seems to be a missing asset error. Could someone explain why this occurs? I can't find it in the webassets-external/ directory and it seems to be generated by Flask.

**Comment by abhisuri97** [comment]
this is a chrome dev tools setting, but i removed the mention of source map from zxcvbn.js
