### ISSUE TITLE
Add password requirements

### ISSUE THREAD

**Issue by sandlerben** [hack4impact/flask-base#12]
@aharelick said "Agree with max and the suggestions from owasp say we should make the minimum 8 characters. They also say that the recommendations may be out of date, but I think it's a good place to start. Also, we should probably add the validator to RegistrationForm and ResetPasswordForm and ChangePasswordForm."

**Comment by maxmcc** [comment]
While we're thinking about this, it might be best to use a password entropy estimator rather than a minimum required length—[this one](https://github.com/dropbox/python-zxcvbn) developed by Dropbox might be good to try out.

**Comment by abhisuri97** [comment]
#37 fix implementing the zxcvbn password check entropy estimator (javascript not python so users can have a live response for password strength)
