### ISSUE TITLE
SECRET_KEY_ENV_VAR_NOT_SET issue and how to fix it

### ISSUE THREAD

**Issue by iSevenDays** [hack4impact/flask-base#123]
I have set everything according to the doc.

However, I see each time SECRET KEY ENV VAR NOT SET! SHOULD NOT SEE IN PRODUCTION.

The key is set in config.env

But  os.environ executes later.

To fix the issue, move the following from "manage.py" to "config.py" above 'class Manager'
```
if os.path.exists('config.env'):
    print('Importing environment from .env file')
    for line in open('config.env'):
        var = line.strip().split('=')
        if len(var) == 2:
            os.environ[var[0]] = var[1]
```

**Comment by abhisuri97** [comment]
Thanks for pointing out this bug. If you'd like to make a PR feel free to do so 👍 If not, I will push it to master by the end of the day.

**Comment by abhisuri97** [comment]
Fixed ref https://github.com/hack4impact/flask-base/commit/8d5cd225bd9c01ef317605f73e46d0dad1146d07
