### ISSUE TITLE
Admin:Invite user - submit button inactive

### ISSUE THREAD

**Issue by Mattpwinchester** [hack4impact/flask-base#130]
Before and after filling in information the submit button is inactive. I don't believe I have changed anything in this app to cause the change in behavior. Is this normal or am I using it incorrectly?

![test](https://cloud.githubusercontent.com/assets/20302042/24047606/ff33cac8-0b04-11e7-8a8c-5dada363396b.png)

**Comment by abhisuri97** [comment]
Hmm...I believe this issue was fixed very recently with https://github.com/hack4impact/flask-base/commit/1e6ad29c14967055fe9b963454e681dd36b1da47  Can you try pulling from master?
