### ISSUE TITLE
Flask flash with forms not working

### ISSUE THREAD

**Issue by Mattpwinchester** [hack4impact/flask-base#131]
I don't understand the flask-base setup of flash with the forms created. What are the steps that I need to do in order to get flash to flash a message on form submission?

Currently am importing in the template:

{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% block scripts %}
{% endblock %}

If there is some macro I need to access or use please let me know.

**Comment by abhisuri97** [comment]
Hey Matt, 
Perhaps it would help if you refer to something like https://github.com/hack4impact/flask-base/blob/master/app/admin/views.py#L110 as an example of how to use flashes.

**Comment by abhisuri97** [comment]
closing. feel free to reopen if still an issue.
