### ISSUE TITLE
Redis on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by sbue** [hack4impact/flask-base#132]
I ran into some issues when trying to set this up on my Windows computer. I installed Flask-base using Bash on Ubuntu on Windows (because Redis does not currently support Windows).

On configuring flask-base, running `honcho start -f Local` would result in `redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.` so I could not launch the app.

I fixed this by following [this guide](http://jessicadeen.com/tech/how-to-configure-redis-server-on-bash-on-ubuntu-on-windows-10-wsl/). For some reason I also had to also edit ` /etc/redis/redis.conf` and replace `port 6379` (default) with something different like `port 6378` and then setting `REDISTOGO_URL=http://localhost:6378` in Flask-base config.env

**Comment by abhisuri97** [comment]
Will link this issue in README 👍 closing for now.

**Comment by Random-Black-Coder** [comment]
The link that @abhisuri97 used is no longer working but I am having the same issue.
