### ISSUE TITLE
Invitation link not allowing user to sign in

### ISSUE THREAD

**Issue by Mattpwinchester** [hack4impact/flask-base#133]
When an admin fills out an invitation request the link sent to the user is of the format:

(server-name)/account/join-from-invite/(user id)/(token)

However, when a user clicks on the invitation link in the email, my users are taken to a page that tells them 'you are already logged in' with a red flash message. If they then try to log in, they are denied. A workaround is to get them to use password reset, then make a new password and login to the account with that. 

I tried doing the same test myself by logging out of my account and using chrome incognito. Both took me to the same screen as the other users and informed me I am already logged in.

**Comment by abhisuri97** [comment]
hey sorry for being late on getting back to you on this. I know that there were some changes made in the login flow a couple of weeks back, perhaps merging the changes would work?

steps i tried:
1) go to the invite form on an admin account (http://localhost:5000/admin/invite-user) 
2) fill out info with right stuff ofc
3) copied link in my email into a separate incognito window. 
4) fill in password
5) log in with new credentials. 

If you are encountering any specific errors in your terminal that would probably be better for me diagnosing the problem.
