### ISSUE TITLE
favicon 404

### ISSUE THREAD

**Issue by Mattpwinchester** [hack4impact/flask-base#134]
I keep getting a favicon icon 404 and I'm not sure where the file is supposed to be or where it is linked:

13:55:56 web.1    | 127.0.0.1 - - [05/Apr/2017 13:55:56] "GET /favicon.ico HTTP/1.0" 404 -

I searched to see if this was an issue before in flask-base and I didn't get any results. Is there a quick fix to this?

**Comment by abhisuri97** [comment]
http://flask.pocoo.org/docs/0.12/patterns/favicon/
