### ISSUE TITLE
Migrate from flask-rq to vanilla rq

### ISSUE THREAD

**Issue by sandlerben** [hack4impact/flask-base#136]
We need to specify max_connections or else the apps will break all the time on the heroku free plans. there is no way to do that with flask-rq.

https://github.com/andymccurdy/redis-py#connection-pools

**Comment by azie-ginanjar** [comment]
@sandlerben could I take on this one?

**Comment by sandlerben** [comment]
Please!

**Comment by azie-ginanjar** [comment]
@sandlerben could you share the link to vanilla rq website? Try to search through google but can not find it.

**Comment by abhisuri97** [comment]
https://github.com/nvie/rq

**Comment by azie-ginanjar** [comment]
@abhisuri97 thanks a lot
