### ISSUE TITLE
Inconsistent documentation: honcho vs. foreman

### ISSUE THREAD

**Issue by and-semakin** [hack4impact/flask-base#139]
README.md says "honcho", but docs/deply.md and docs/setup.md still use "foreman". What should I use?

**Comment by sandlerben** [comment]
Good catch! `foreman` is the original (Ruby-based) tool for managing Procfile based applications. `honcho` is fully API compatible and is Python-based. In the interest of sticking with just a Python stack, I'll change `deploy.md` to mention `honcho`.

**Comment by and-semakin** [comment]
Changes are also needed in [docs/setup.md](https://github.com/hack4impact/flask-base/blob/master/docs/setup.md). Thank you!

**Comment by and-semakin** [comment]
And [documentation on flask-base website](http://hack4impact.github.io/flask-base/setup/) also need fixes.

**Comment by sandlerben** [comment]
@abhisuri97 I updated setup.md, how do we update the readthedocs site?
