### ISSUE TITLE
THIS APP IS IN DEBUG MODE. YOU SHOULD NOT SEE THIS IN PRODUCTION.

### ISSUE THREAD

**Issue by chppppp** [hack4impact/flask-base#144]
In my config.env I have the line FLASK_CONFIG="production" but I still get the message that I am in Debug mode. I have tried exporting the env value but still no luck.  

Sorry if this is a noob question :) Thank you very much!

**Comment by chppppp** [comment]
Issue closed. i'm an idiot. 

Thanks

**Comment by abhisuri97** [comment]
This error can be ignored. what happens is when we initially load in the scripts necessary to start the app, it assumes the default config at first (development) before it reads in the actual config mode. Kinda an unintentional consequence of having the flask manager handle launching the app. If you have an idea about how to fix it (or make the error message better), let me know.

**Comment by chppppp** [comment]
Thank you!! I had thought this so I had closed my issue, but then I started thinking more and re-opened. 

I will close this issue and if I come up with anything clever I will issue a PR. Thank you!

**Comment by sandlerben** [comment]
Am I understanding this correctly @abhisuri97? No matter how the app is configured the warning is always shown? If so, this seems like a bug.
