### ISSUE TITLE
403 with default login

### ISSUE THREAD

**Issue by chppppp** [hack4impact/flask-base#145]
I am able to launch the app no issues but after creating an account or using the default I get a 403 error.

**Comment by abhisuri97** [comment]
are you sure you ran `python manage.py recreate_db` and for the credentials for the admin side are you using `flask-base-admin@example.com` and `password`?

**Comment by chppppp** [comment]
Yes! I also ran

python manage.py setup_dev
python manage.py setup_prod

Thank you

**Comment by chppppp** [comment]
I also receive a 403 when registering a user

**Comment by chppppp** [comment]
My fault. 

I copy/pasted a load balancer config that was denying POST requests. 

Thank you,
