### ISSUE TITLE
Find easier way to create first admin

### ISSUE THREAD

**Issue by sandlerben** [hack4impact/flask-base#15]
See discussion at https://github.com/hack4impact/women-veterans-rock/pull/1

**Comment by abhisuri97** [comment]
Does this still need work?

**Comment by sandlerben** [comment]
I think this is fine. Maybe we can merge the approach used by cac into flask-base

> Each team can set an admin account which is always created when they call setup_dev. For example, for GPCAH, we had an account ben@ben.com with password password.

**Comment by abhisuri97** [comment]
Fairly easy way to do this (already in the application):
`python manage.py runserver`. 
Go to Register. Create an account with an email matching ADMIN_EMAIL found in config.py
Make sure that `python manage.py setup_dev` has been called first

OR 

Start an app shell. 
`python manage.py shell`
Create user instance with email = ADMIN_EMAIL found in config.py

```
>>> admin = User(email = "flask-base-admin@example.com", password="something", confirmed=1)
>>> db.session.add(admin)
>>> db.session.commit()
```

Administrator is created provided setup_dev() was called and roles were initialized.
