### ISSUE TITLE
Example of How to use the redis background queue?

### ISSUE THREAD

**Issue by kc1** [hack4impact/flask-base#152]
Thanks for putting this project together. I've written https://stackoverflow.com/questions/48750515/how-to-access-redis-connection-in-background-task. Can you give an example of How to background a  view function . Its not clear to me how the pieces fit together.

**Comment by abhisuri97** [comment]
Sure. Take a  look  at the  code block starting here: 

https://github.com/hack4impact/flask-base/blob/5676d8bad84e995bb0d8f4c3a495af0b845fee6f/app/account/views.py#L44  

basically just  follow  that general syntax ie  

`get_queue().enqueue(name_of_function, arg1=val1, arg2=val2...)`

**Comment by kc1** [comment]
Dude, you are amazing! If only I'd known this 3 weeks ago. In my code I've added:

@login_required
@main.route('/selected2')
def background_selected():
    j=  get_queue().enqueue(some_long_calculation3)
    return (j.get_id())

Which returns the job # 6f10f8d6-7ec9-4c31-9ed4-c05ca3 ( I assume ). Just for my understanding, on heroku you have a 30 second request timeout. My function , some_long_calculation3() , takes 1-2 minutes to run which is why I need to background it. I'm planning on running polling requests based on https://realpython.com/blog/python/flask-by-example-implementing-a-redis-task-queue/ , to let me add the result to the dom or a db. Looking at the code from the article:

    @app.route("/results/<job_key>", methods=['GET'])
    def get_results(job_key):

    job = Job.fetch(job_key, connection=conn)

    if job.is_finished:
        return str(job.result), 200
    else:
        return "Nay!", 202

How do I get a Job object, so that I can look up the result. I don't see it in

https://github.com/mattupstate/flask-rq/blob/master/flask_rq.py

EDIT:

sorry: its at 'working with queues' in http://python-rq.org/docs/
