### ISSUE TITLE
Allowed to log in even before confirming email

### ISSUE THREAD

**Issue by sandlerben** [hack4impact/flask-base#17]
Steps to reproduce:
1. Make an account
2. Don't confirm email
3. Log in with account

Expected
4. See message that asks to reconfirm email and you are blocked from doing other user things

Actual
4. See message that asks to reconfirm email and you _can_ do other user things

**Comment by aharelick** [comment]
@sandlerben, @jondubin: How do people feel about having another decorator like `@confirmed` to put on top of routes that require it. Understandably, this may be a little excessive. I think the overlap between `@login_required` and something like `@confirmed` would be pretty large, but just wanted to gauge opinions.

**Comment by sandlerben** [comment]
Could we create a better version of `login_required` and put it in decorators.py?

**Comment by jondubin** [comment]
How about we pass an argument into the decorator to indicate whether the acct needs to be confirmed or not?

**Comment by sandlerben** [comment]
That's a good idea. Every endpoint that is login protected should also require confirmation _except_ the confirm account endpoint.

**Comment by abhisuri97** [comment]
Is this still an error? I just tried this in my app and the expected behavior is what is happening currently. I think that the following found in app/account/views.py takes care of the issue (or at least it should):

```
@account.before_app_request
def before_request():
    """Force user to confirm email before accessing login-required routes."""
    if current_user.is_authenticated() \
            and not current_user.confirmed \
            and request.endpoint[:8] != 'account.' \
            and request.endpoint != 'static':
        return redirect(url_for('account.unconfirmed'))


@account.route('/unconfirmed')
def unconfirmed():
    """Catch users with unconfirmed emails."""
    if current_user.is_anonymous() or current_user.confirmed:
        return redirect(url_for('main.index'))
    return render_template('account/unconfirmed.html')
```

**Comment by sandlerben** [comment]
It's possible I fixed it without closing the issue. I'll check and update
this issue.

**Comment by abhisuri97** [comment]
permission to close the issue? tested and it seems to be fixed.

**Comment by sandlerben** [comment]
yes this looks fixed! sorry for the delayed response
