### ISSUE TITLE
Every route running twice

### ISSUE THREAD

**Issue by samanyougarg** [hack4impact/flask-base#172]
Hi there

Thanks a lot for developing such a wonderful boilerplate. I have been using it for a couple of projects but just noticed that each route is being run twice.
For example, if you log something in main.index
`current_app.logger.info("Test")`
it will be logged twice in the terminal.

Please let me know how this error can be fixed.

Thanks

**Comment by eoinieo** [comment]
I'm pretty new to this project but I'd be surprised if every route is being called twice.
This is likely a logging issue.
To validate this, you could try a single use of:
print('test print %s' % strftime("%Y-%m-%d %H:%M:%S", gmtime()), file=sys.stderr)
with the necessary imports:
from __future__ import print_function
from time import gmtime, strftime

If this line only prints once it def points to the logging.

**Comment by abhisuri97** [comment]
@samanyougarg I am unsure exactly how to  reproduce this. Could you paste a full code snippet?

**Comment by samanyougarg** [comment]
Hi all,
Sorry for the late response.

I tried eoinieo's suggestion but it does the same for print as well.

To reproduce the error, just add a print or logger statement at the start of any of the routes.
For example, I did this on index route - 

```
@main.route('/')
def index():
    print('test print %s' % strftime("%Y-%m-%d %H:%M:%S", gmtime()), file=sys.stderr)
    return render_template('main/index.html')
```

This will print twice, suggesting that each route is being run twice.

**Comment by sandlerben** [comment]
@samanyougarg it's extremely unlikely that each route is being run twice. Many routes handle important business logic (e.g. queue a task to send an email, update the database) and if every route was running twice, we would surely have noticed by now. Plus, this would be a problem with flask, not flask-base, if it is a problem.

I just ran unmodified flask-base locally and added the line `print('here')` to the `/` route and it only printed once.

**Comment by sandlerben** [comment]
I'm going to close this issue feel free to reopen if you think it's a problem with flask-base.

**Comment by TyrelCB** [comment]
I'm seeing the same behavior (route appears to run twice when requested once), however only with one specific route.

Only way I can get around this is to:

1. redirect to static
2. disable the function call get_tv_shows_v1()

Not sure why this function call would cause this issue. It's using requests to make a couple external calls but defiantly not to /update_tv or even the app itself. Returns and ordered dict.

```
@app.route('/update_tv', methods=['GET'])
def update_tv():
    if (request.remote_addr == '127.0.0.1') or (request.headers.get('Host') == '192.168.1.254:88'):
        local_remote = 'local'
    else:
        local_remote = 'remote'
    tv_show_list = get_tv_shows_v1(local_remote=local_remote)
    static_file = render_template('movie_list.html', tv_show_list=tv_show_list)
    wo.write_to_file('static/tv_list.html', static_file)
    #return redirect("/static/tv_list.html", code=302)
    return static_file
```

```
 * Serving Flask app "media_center" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:88/ (Press CTRL+C to quit)
 * Restarting with stat
CEC Failed
 * Debugger is active!
 * Debugger PIN: 264-455-304
Better.Call.Saul.S03E01
Better Call Saul
('Better Call Saul', 'S03')
127.0.0.1 - - [26/Mar/2020 00:44:27] "GET /update_tv HTTP/1.1" 200 -
127.0.0.1 - - [26/Mar/2020 00:44:27] "GET /right-arrow.svg HTTP/1.1" 404 -
Better.Call.Saul.S03E01
Better Call Saul
('Better Call Saul', 'S03')
127.0.0.1 - - [26/Mar/2020 00:44:28] "GET /update_tv HTTP/1.1" 200 -
```
