### ISSUE TITLE
I found  a issue, I'm not sure wether it's a problem , pls check.

### ISSUE THREAD

**Issue by skyismine2010** [hack4impact/flask-base#176]
During sending email , the function in flask_mail.py  163 line

    def configure_host(self):
        if self.mail.use_ssl:  --- but i'ts  string type, not a boolean type.
            host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
        else:
            host = smtplib.SMTP(self.mail.server, self.mail.port)

        host.set_debuglevel(int(self.mail.debug))

pls check , Tks
BR from yqqls

**Comment by sandlerben** [comment]
Can you link to where it's defined?

**Comment by skyismine2010** [comment]
It's defined in flask_mail.py  line:549 (master branch)
self.mail.use_ssl is assigned in _mail construct function by config.get
like this:
config.get('MAIL_USE_TLS', False)
the config object is  inherited from dict ， it's defined in flask/config.py , it maybe string type in some condition.

**Comment by skyismine2010** [comment]
> Can you link to where it's defined?

It's defined in flask_mail.py line:549 (master branch)
self.mail.use_ssl is assigned in _mail construct function by config.get
like this:
config.get('MAIL_USE_TLS', False)
the config object is inherited from dict ， it's defined in flask/config.py , it maybe string type in some condition.

**Comment by sandlerben** [comment]
Sounds like you think there might be a bug in the library. Feel free to make an issue on their repo and link it here.

**Comment by sandlerben** [comment]
I think this is intended behavior though
