### ISSUE TITLE
config.env database_url not working

### ISSUE THREAD

**Issue by tangyiming** [hack4impact/flask-base#181]
i run a postgresql container in docker,
and add this in config.env:
`DATABASE_URL=postgresql://postgres:docker@localhost:5432/postgres`
but every time i run:
`python manage.py setup_dev`
it will creates data-dev.sqlite

ps:the db name and password is correct,i can use the command to connect:
`psql -h localhost -U postgres -d postgres`

**Comment by Euphorbium** [comment]
@Tangyiming I haven't tested this, but have you tried setting  `SQLALCHEMY_DATABASE_URI` instead?

**Comment by abhisuri97** [comment]
@Tangyiming the reason it does that is that you have the app in development mode. Change`FLASK_CONFIG=production` to get the ability to connect  to a db. If you want to connect to a  Db in dev mode then look at lines: https://github.com/hack4impact/flask-base/blob/2278d3f5d26e1c24f58359965cba46281619759b/config.py#L78 

Basically set`DEV_DATABASE_URL=yoururlhere` in `config.env`.

**Comment by tangyiming** [comment]
@abhisuri97 thanks,it works.
