### ISSUE TITLE
Can't install postgresql

### ISSUE THREAD

**Issue by JeanPierreFig** [hack4impact/flask-base#183]
For some reason I can't install postgresql, obviously there's a missing resource but had anyone else has had this problem before? 
<img width="920" alt="screen shot 2019-02-26 at 6 29 28 pm" src="https://user-images.githubusercontent.com/13212319/53456553-80f73980-39f4-11e9-94cf-b32fce872b76.png">

**Comment by abhisuri97** [comment]
I think this would be an appropriate question for more postgres oriented forums. Try posting in there first (personally, I haven't encountered this issue). I'll close the issue for now b/c it isn't relevant to flask-base specifically (feel free to reopen).
