### ISSUE TITLE
migrate and upgrade

### ISSUE THREAD

**Issue by trinanda** [hack4impact/flask-base#186]
How to run db change command in this boilerplate..?, like` flask db migrate` and `flask db upgrade` command.

**Comment by abhisuri97** [comment]
This would be done via `python manage.py db insert-migrate-command-here`. See https://github.com/hack4impact/flask-base/blob/c1d1fca1bb3380b49aca2d73749d7098977dcef2/manage.py#L24

**Comment by trinanda** [comment]
Very thanks @abhisuri97 :)
