### ISSUE TITLE
Making flask-base a template

### ISSUE THREAD

**Issue by nk9** [hack4impact/flask-base#188]
Since this is a template project, it would be helpful if you [ticked the "Template repository" box in settings](https://help.github.com/en/articles/creating-a-template-repository). This will make is super simple for people to copy the repo, renaming it as needed, to get started hacking on their own account. It will add a big green button to the main project page:

![Screen Shot 2019-08-16 at 13 04 58](https://user-images.githubusercontent.com/3646730/63166521-8f7af100-c026-11e9-911b-3ee55be5277e.png)

**Comment by abhisuri97** [comment]
Done :) Thank you for the suggestion.
