### ISSUE TITLE
Installing on Windows? Unable to get redis installation

### ISSUE THREAD

**Issue by ripgith** [hack4impact/flask-base#195]
Everytime I start a project I try to figure out if it will work in a Windows environment. Without finely reading the installation I didn't notice that redis doesn't contain installation instructions for Windows.

Looking through the rest of the innertubes it seems that there are some workarounds but are imperfect. They include docker images in a hypervisor, a beta/paid product (memurai).

Should I even try to use this in Windows or just move the effort to Linux/Mint?

**Comment by abhisuri97** [comment]
Clarifying. have you tried this solution linked in the readme? https://github.com/hack4impact/flask-base/issues/132

**Comment by ripgith** [comment]
Thank you for pointing out the use of WSL. It seems like it will work very nicely. Now I believe I'll move my full development stack into the Ubuntu workspace since the interoperability between Windows and WSL appears excellent.
