### ISSUE TITLE
how to add mailgun credentials?

### ISSUE THREAD

**Issue by whatsdis** [hack4impact/flask-base#196]
how do i make this work with mailgun?

**Comment by whatsdis** [comment]
nvm this project seems abandoned now. time to uninstall

**Comment by abhisuri97** [comment]
Sorry it took a while to get back to you. Just got back from school. I am unsure if this can work with mailgun; however, if they do have a way to send via an SMTP server, it can definitely work.

The relevant lines you may want to change are around here: 
https://github.com/hack4impact/flask-base/blob/adde920f4d22cf920f3260510df77f5bae36b8e7/config.py#L33
And change the relevant config variables in config.env.
