### ISSUE TITLE
Heroku bundling issues

### ISSUE THREAD

**Issue by MapZombie** [hack4impact/flask-base#199]
Hi, I am having a similar issue with #110, it seems like script ordering problems. This is after pushing to a heroku app. However as localhost everything renders correctly and does not throw the same errors.
Has anybody run into script bundling issues this when deploying to Heroku?
```

Uncaught SyntaxError: Unexpected token '!'
dashboard.js:1000 Uncaught TypeError: $(...).jsGrid is not a function
    at creategrid (dashboard.js:1000)
    at dashboard.js:1069
creategrid @ dashboard.js:1000
(anonymous) @ dashboard.js:1069

jquery-3.4.1.min.js:2 Uncaught TypeError: $(...).sortable is not a function
    at HTMLDocument.<anonymous> (dashboard.js:59)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)
```

**Comment by abhisuri97** [comment]
Are you seeing any other errors? Dashboard.js doesn't look like a dependency we have, so perhaps you should adjust app/assets.py to account for that file existing.

https://github.com/hack4impact/flask-base/blob/a10c66a16d46b04dbdf34ddced0387a080ce0b99/app/assets.py#L9

**Comment by abhisuri97** [comment]
Closing unless there are any other issues (feel free to reopen as you see fit).
