### ISSUE TITLE
celery integration

### ISSUE THREAD

**Issue by rishkarajgi** [hack4impact/flask-base#201]
How to integrate celery into this app?

**Comment by abhisuri97** [comment]
Hi there, 
Sorry for getting to this so very late. 

So right now, we use an already baked in version of a redis task queue manager as implemented in flask_rq. You can find its instantiation here: https://github.com/hack4impact/flask-base/blob/a4945cbc5bf9285462d4b1d0c22515c2c63b78f1/app/__init__.py#L8 

Essentially, the queue is only really used in a couple of places. One is in admin/views and the other is in accounts/views. Both times it is just used for emailing. So if you want to use celery instead, just go ahead and rip out any reference to flask_rq in those files and replace it with your own celery integration. 

The main calls to replace in the application are get_queue() calls.  Does that help?

**Comment by abhisuri97** [comment]
Closing. Feel free to reopen if you have any other issues!
