### ISSUE TITLE
Icon documentation

### ISSUE THREAD

**Issue by SelfhostedPro** [hack4impact/flask-base#205]
Hey guys, do you have any links to documentation on how icons work with your templates?

**Comment by abhisuri97** [comment]
Hi there, could you refer to the semantic-ui library and see if that addresses your concerns? That's what we use for CSS. https://semantic-ui.com/ There should be a section on icons on that site.

**Comment by SelfhostedPro** [comment]
I was able to find it there after some digging. It may be good to have a link pointing to it in the documentation though.
