### ISSUE TITLE
User authentication not working in mobile view

### ISSUE THREAD

**Issue by danchann** [hack4impact/flask-base#220]
This is tested in the default flask-base instance.

https://user-images.githubusercontent.com/3872230/141717672-9ae6089f-0225-4855-8d97-76d3380c4009.mov

**Comment by abhisuri97** [comment]
I'm having a bit of difficulty reproducing this. Does authentication work normally if you're not in the mobile view?

**Comment by s9111477** [comment]
> I'm having a bit of difficulty reproducing this. Does authentication work normally if you're not in the mobile view?

Yes, the authentication is working fine in desktop view.

**Comment by danchann** [comment]
> I'm having a bit of difficulty reproducing this. Does authentication work normally if you're not in the mobile view?

Yes, authentication is working normally in desktop view but once switched to mobile view, the user becomes not authenticated.

https://user-images.githubusercontent.com/3872230/142157470-c0c85c8c-d033-45b9-98cc-5d8620e779a6.mov

**Comment by danchann** [comment]
I verified that the user is lost as soon as it is switched to mobile view
Desktop
![image](https://user-images.githubusercontent.com/3872230/142160093-b7f7cad2-4099-4ff3-a94e-ce2fb16bfee2.png)
Mobile
![image](https://user-images.githubusercontent.com/3872230/142159561-121db025-ed74-4a14-8f92-38756bd1f02c.png)

**Comment by danchann** [comment]
Looks like it's due to the session protection feature of flask-login. 
The default protection in this repo is set to 'strong` mode, when the view is changed it seemed that the entire session is deleted.
See https://flask-login.readthedocs.io/en/latest/#session-protection

**Solution:**
Change the login_manager.session_protection to from "strong" to "basic".
https://github.com/hack4impact/flask-base/blob/f58ca736ec3d7d3df599b6fe3af3d15f21d1b985/app/__init__.py#L24

**Comment by abhisuri97** [comment]
Fixed. Could you pull again and see if that changes anything?

**Comment by danchann** [comment]
Yep, it's working fine now. Closing this.
