### ISSUE TITLE
Give flask-base a real task queue

### ISSUE THREAD

**Issue by sandlerben** [hack4impact/flask-base#26]
Right now, async code (e.g. `send_email`) is implemented with threads). We should have a worker process always running which completes tasks from the task queue instead. One problem with the current approach is that clients of the `send_email` function do not know that it is asynchronous unless they read the implementation. I would much prefer something like this (with [rq](http://python-rq.org/))

``` python
result = task_queue.enqueue(send_email, <args>)
```

**Comment by jondubin** [comment]
For H4I use, would we setup a hosted Redis server for clients to connect to, or would we add Redis as a dependency for Flask-Base?

**Comment by aharelick** [comment]
I think we would say that a hosted redis instance is necessary and also add it to the app.json. https://elements.heroku.com/addons/heroku-redis

**Comment by sandlerben** [comment]
I would add redis as a dependency. Exactly what @aharelick said.

**Comment by abhisuri97** [comment]
See Ben's PR.
