### ISSUE TITLE
Security enhancements

### ISSUE THREAD

**Issue by maxmcc** [hack4impact/flask-base#3]
- Double-check that CSRF protection is working properly
- Other features from flask-security package that might be missing

**Comment by abhisuri97** [comment]
It is probably best that we remove our default secret key from config...or you know actually generate one (please correct me if we do that already).

**Comment by sandlerben** [comment]
Any deployment should set the `SECRET_KEY` environment variable.

**Comment by aharelick** [comment]
Yeah, we should remove that default value. I don't think the application should work in production if you haven't set the environment variable yourself.

**Comment by sandlerben** [comment]
Ok that's fair.

**Comment by abhisuri97** [comment]
`SECRET_KEY` check before deployment taken care of. CSRF is working on all pages.
