### ISSUE TITLE
Rearrange all import statements in alphabetical order

### ISSUE THREAD

**Issue by armant** [hack4impact/flask-base#34]

**Comment by sandlerben** [comment]
It probably shouldn't just be in alphabetical order. It should be split up into
- Python standard library
- Python external libraries
- Our own code

Each section can be alphabetized. Right now, our imports are actually quite inconsistent. I wonder if there is a tool like [`goimports`](https://godoc.org/golang.org/x/tools/cmd/goimports) which formats imports automatically.

**Comment by armant** [comment]
^yes, exactly, that was the format used at my internship (and within these groups alphabetically )

**Comment by abhisuri97** [comment]
doing this as i comment
