### ISSUE TITLE
Let's change indentation step from 4-space to 2-space?

### ISSUE THREAD

**Issue by armant** [hack4impact/flask-base#36]

**Comment by sandlerben** [comment]
Why? I think the PyCharm default is 4-space.

**Comment by abhisuri97** [comment]
I don't see a reason to convert everything we have at the moment to 2 space. Unless you have a specific reason for doing so

**Comment by maxmcc** [comment]
According to [PEP 8](https://www.python.org/dev/peps/pep-0008/#indentation), the preferred number of spaces is 4.
