### ISSUE TITLE
Make sure all db.sessions are committed

### ISSUE THREAD

**Issue by sandlerben** [hack4impact/flask-base#38]
After a `db.session.add` the session must also be committed. This has led to strange bugs in cac where locally everything works but sessions that aren't committed in production **don't work**.

**Comment by sandlerben** [comment]
One file with this problem is user.py see https://github.com/hack4impact/clean-air-council/commit/e5b288de64c9f9f9a0b0435cd7a35d0decdba782

**Comment by abhisuri97** [comment]
I know sqlalchemy has an option for setting `autocommit=True` whenever initiating the session object. It should automatically commit whenever there is a change made to the db.

**Comment by sandlerben** [comment]
This is a great idea. Any reason why we shouldn't do it that way?

**Comment by abhisuri97** [comment]
SQLAlchemy strongly recommends not using `autocommit=True` for some reason which I am reading up on right now (default `autocommit=False`)

**Comment by abhisuri97** [comment]
I think it would be best to close this issue. the db.session.commit is in place as a sort of fallback. If your application crashes midway through a process where database changes are happening, nothing will change the db unless the final .commit line is hit. If every line was automatically committed (as would happen in `autocommit=True` then you would have half filled records...messy situation

**Comment by abhisuri97** [comment]
permission to close?

**Comment by sandlerben** [comment]
Okay I just went through and fixed a few places where the sessions were not being committed

**Comment by abhisuri97** [comment]
Yeah... I am not sure whether this was a commit error or not. So, looking through `config.py` the setting SQLALCHEMY_COMMIT_ON_TEARDOWN is set to True meaning that (according to the SQLAlchemy docs) all non-committed sessions at the end of the app context will be committed. But regardless, it is best to commit anyway. Closing unless something else comes up.
