### ISSUE TITLE
Dynamic Asset Reloading

### ISSUE THREAD

**Issue by abhisuri97** [hack4impact/flask-base#46]
It would be best to figure out a non-intrusive way to automatically reload assets on file change and propagate those changes to the browser. This plugin may be helpful, but it wraps our entire flask app within a LiveReload Server. https://pypi.python.org/pypi/livereload

**Comment by sandlerben** [comment]
How necessary is this?

**Comment by abhisuri97** [comment]
Not necessary. No real way to do this without importing the livereload server.
