### ISSUE TITLE
Port flask-base to python3

### ISSUE THREAD

**Issue by sandlerben** [hack4impact/flask-base#52]
Steps this will probably require
1. Run [python 2to3](https://docs.python.org/2/library/2to3.html) on our application code
2. Reinstall python3 versions of our dependencies

**Comment by yoninachmany** [comment]
lets make sure to do this before we start projects this sem

**Comment by sandlerben** [comment]
Agreed

**Comment by sandlerben** [comment]
Two of flask-bases dependencies haven't migrated to python 3 yet:
- flask-rq
- flask-sslify

I made issues on both repos. Let's close this issue for now and revisit in a few months or next year.
