### ISSUE TITLE
Add auto-formatting to flask-base

### ISSUE THREAD

**Issue by sandlerben** [hack4impact/flask-base#53]
From working on Go and working at Google (where most code is auto-formatted) I've noticed that there are immense benefits to auto-formatting code.
1. Code style and conformation to standards, like pep8, are ensured.
2. Writing code is faster.
3. Less cognitive load, it's one less thing to worry about.
4. No arguments about style.
5. If all of our python code is formatted the same, getting up to speed with code you didn't write will take less effort.
6. Diffs show actual code, not 'diff noise' where someone adds a space or changes formatting.

**Comment by yoninachmany** [comment]
Great thought and great points. Some questions/comments.
1. How do you autoformat code?
2. Let's make sure to do something similar to this with other bases.
3. Can we do this easily for projects that forked?

Code LGTM

**Comment by sandlerben** [comment]
1. You install a yapf extension in your editor (they have one for vim, atom, etc) or run it from the command line.
2. Agreed.
3. Yes, it shouldn't be too hard. Though I think it would only be necessary for projects under active development (like maps4all).

**Comment by sandlerben** [comment]
Alex endorses this
