### ISSUE TITLE
ImportError: No module named faker

### ISSUE THREAD

**Issue by yoninachmany** [hack4impact/flask-base#55]
do other people get this when setting up? I don't see faker in either of the requirements files

**Comment by aharelick** [comment]
Faker is part of the fake-factory package that's in the dev requirements. But apparently the makers are going to deprecate fake-factory and just start using Faker at the end of the year so we should probably switch that import: https://pypi.python.org/pypi/fake-factory.

**Comment by sandlerben** [comment]
make a PR!

**Comment by abhisuri97** [comment]
#56
