### ISSUE TITLE
Branches in "Extensions" part of README.md either merged or closed

### ISSUE THREAD

**Issue by yoninachmany** [hack4impact/flask-base#57]
should probably move https://github.com/hack4impact/flask-base#extensions info to https://github.com/hack4impact/flask-base#whats-included

**Comment by yoninachmany** [comment]
remove "only valid on gulp-static-watcher-branch" https://github.com/hack4impact/flask-base#optional-only-valid-on-gulp-static-watcher-branch-use-gulp-to-live-compile-your-files

**Comment by yoninachmany** [comment]
@sandlerben @weronica can you explain status of `admin-edit-static-pages` branch? it is currently included in https://github.com/hack4impact/flask-base#extensions, but https://github.com/hack4impact/flask-base/pull/23 (related to branch) was closed with unmerged commits, and the branch is stale

<img width="1002" alt="screen shot 2016-10-12 at 6 39 02 pm" src="https://cloud.githubusercontent.com/assets/4250521/19330295/93a32d36-90ab-11e6-8d22-ce496ef4f00d.png">

**Comment by abhisuri97** [comment]
I am not sure as to why we keep these features on separate branches. For example gulp static watcher is just one file that runs independently of the `runserver` command. I am for merging these branches into master as I do not see any harm in keeping them in our code base.

**Comment by sandlerben** [comment]
@abhisuri97 no definitely don't just merge anything without a PR

**Comment by sandlerben** [comment]
this is something that requires discussion!

**Comment by abhisuri97** [comment]
Oh no lol i mean I am definitely advocating that we consider merging them into master. Of course following regular procedure.

**Comment by sandlerben** [comment]
ok ok

**Comment by abhisuri97** [comment]
done
