### ISSUE TITLE
should we clone using ‘ssh’ instead of ‘http’?

### ISSUE THREAD

**Issue by yoninachmany** [hack4impact/flask-base#62]
if so, you may have to create an [ssh keypair](https://help.github.com/articles/generating-an-ssh-key/) to properly authenticate

**Comment by abhisuri97** [comment]
This is on a user by user basis and is just generalizable for github in general. I don't think it is an issue specific to flask base. Let me know if you feel this should remain open.

**Comment by yoninachmany** [comment]
@abhisuri97 in reference to https://github.com/hack4impact/flask-base#clone-the-repo - should we keep as http? in women veterans rock, alex harelick told us to `ssh`

**Comment by abhisuri97** [comment]
It really doesn't matter how you do cloning. ssh is just more convenient since you dont have to type in your username and password each time you push.

**Comment by rileynwong** [comment]
I think if we're setting the h4i standard for cloning repos in the flask-base readme, we should add a dev step for using `ssh` instead. it would be better for all of our members downstream to clone using `ssh` as part of the project setup imo

**Comment by abhisuri97** [comment]
https://help.github.com/articles/which-remote-url-should-i-use/

As I mentioned earlier, it doesn't matter and I don't see this as an issue. Either one should not affect the repo itself nor how people interact with it. This may be something to include in the README if people feel strongly about it. If so, open a PR.

**Comment by sandlerben** [comment]
FWIW I use https and I have some set-up where I don't type in my password

I think that this could go in the README - but maybe it is better suited for the wiki?

**Comment by abhisuri97** [comment]
Yes. It should go in the wiki. permission to close?

**Comment by yoninachmany** [comment]
> Nancy: I think if we're setting the h4i standard for cloning repos in the flask-base readme
> i agree - let's keep stuff in readme
> 
> Ben: FWIW I use https and I have some set-up where I don't type in my password
> why is this better than ssh?
