### ISSUE TITLE
should we require flake8?

### ISSUE THREAD

**Issue by yoninachmany** [hack4impact/flask-base#63]
Install flake8
## might need sudo when installing globally

$ sudo pip install flake8

Set Up flake8 Hooks
## add the hook to check style on ‘git commit’ (run in root of project)

$ flake8 --install-hook
## setting the strict config means it will block the commit if there are errors

$ git config flake8.strict true

**Comment by abhisuri97** [comment]
Yapf formatting will take care of our formatting issues. In addition our tests will check to see if `python manage.py format` has been applied to a branch before being merged in via a pull request. If it detects `python manage.py format` has not been run, then the pull request circle tests will not pass.
