### ISSUE TITLE
should we include a .env file and instructions that an mail username and password are required?

### ISSUE THREAD

**Issue by yoninachmany** [hack4impact/flask-base#64]
include dummy MAIL_USERNAME and MAIL_PASSWORD and tell user that they need to fill out

**Comment by abhisuri97** [comment]
Yes. We should probably include instructions for this. I do not think that we should remove .env from our .gitignore though as this can lead to accidental commits including sensitive user information.

**Comment by abhisuri97** [comment]
#66
