### ISSUE TITLE
Add google analytics boilerplate and instructions

### ISSUE THREAD

**Issue by sandlerben** [hack4impact/flask-base#7]

**Comment by abhisuri97** [comment]
does anyone know how to do analytics? I mean we could just include the boilerplate google analytics script on every page

**Comment by sandlerben** [comment]
Yes, we just have to include the analytics `<script>` in the base html file. I don't think that anything is necessary in flask-base except maybe a comment on where to put the code.

**Comment by yoninachmany** [comment]
where is linked pr?

**Comment by sandlerben** [comment]
This doesn't need a PR. The boilerplate can you easily copied and pasted
from Google when setting up analytics.
