### ISSUE TITLE
Add gem install sass to README

### ISSUE THREAD

**Issue by sandlerben** [hack4impact/flask-base#70]
This has been a problem for a while! Let's fix it

**Comment by abhisuri97** [comment]
Do we need to do this? I feel that the flask Bundle will preprocess everything from scss to css. Then again I could be mistaken. Ref `app/assets.py`

**Comment by sandlerben** [comment]
Stephanie got an error until she installed sass. This _definitely_ used to be an issue, has it been fixed with some change to flask-base?

**Comment by abhisuri97** [comment]
ah if that is an issue. then yeah go ahead and just add it to the readme

**Comment by abhisuri97** [comment]
done
