### ISSUE TITLE
Should we add a Static Analysis Tool like Code Climate?

### ISSUE THREAD

**Issue by yoninachmany** [hack4impact/flask-base#85]
> A good code review process is essential to writing good code. But certain code problems are difficult for humans to spot. Duplication, for example. If new code is an exact duplicate of code from an existing file in a project, that might not be caught in a code review. Static analysis tools catch duplication, security concerns, and more.
https://github.com/18F/development-guide/blob/master/project_setup/README.md

<img width="993" alt="screen shot 2016-12-11 at 4 18 31 pm" src="https://cloud.githubusercontent.com/assets/4250521/21083428/98025d92-bfbe-11e6-9266-9a48c22eff88.png">

**Comment by sandlerben** [comment]
what static analysis tool?

**Comment by yoninachmany** [comment]
CodeClimate provides 15 day trial w no CC info

**Comment by sandlerben** [comment]
how much is their paid plan?
 





On Mon, Dec 12, 2016 3:27 PM, Yoni Nachmany notifications@github.com
wrote:
CodeClimate provides 15 day trial w no CC info

**Comment by yoninachmany** [comment]
<img width="398" alt="screen shot 2016-12-12 at 5 26 43 pm" src="https://cloud.githubusercontent.com/assets/4250521/21119358/32f73d28-c090-11e6-8b9f-ddfda2d58487.png">

just need to add cc info, i think
