### ISSUE TITLE
For Windows, need to change ".env" to "<filename>.env".

### ISSUE THREAD

**Issue by gitmeister** [hack4impact/flask-base#94]
Changes are in "manage.py".

**Comment by abhisuri97** [comment]
Noted, we can definitely switch to a "filename.env" format in general. Curious, what version of windows are you running? I want to see if i can replicate this on my end.

**Comment by gitmeister** [comment]
This is on Windows 7 but the naming should be fairly consistent across all versions of XP and above. The "." separates <filename> from the <extension> but, oddly, you can have ".somename.someextension".

**Comment by abhisuri97** [comment]
@gitmeister can you check out the PR (#97) and see if that fixes your issue?
